# Generated by Django 3.0.4 on 2020-03-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usuari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuari',
        ),
    ]
